# -*- coding: utf-8 -*-
"""1.5sec

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-8UOQHbMGol7H2DvrsS5hvv1W40vYFPZ
"""

!rm -rf /content/Shared-Parkinson
!git clone -b fix-subject-id https://github.com/HUFS-TRACE/Shared-Parkinson.git

import numpy as np, glob, os
all_npz = glob.glob("/content/Shared-Parkinson/**/*.npz", recursive=True)
files = sorted([f for f in all_npz if "_all[최종]" in f])

print("전체:", len(files))
print("data1:", len([f for f in files if "data1" in f]))
print("data2:", len([f for f in files if "data2" in f]))
print("data3:", len([f for f in files if "data3" in f]))

t = [f for f in files if "104-pd-a-01" in f]
print("\n104-pd-a-01 찾음:", len(t))
if t:
    d = np.load(t[0], allow_pickle=True)
    print("subject_id:", int(d['subject_id']), "| y:", int(d['y']), "| X:", d['X'].shape)

import re
from collections import Counter

diffs, label_bad, badname = Counter(), [], []
for p in files:
    b = os.path.basename(p)
    m = re.match(r'(\d+)-(hc|pd)-(.+)\.npz$', b)
    if not m:
        badname.append(b); continue
    f_id, f_y = int(m.group(1)), (0 if m.group(2)=='hc' else 1)
    d = np.load(p, allow_pickle=True)
    diffs[int(d['subject_id']) - f_id] += 1
    if int(d['y']) != f_y:
        label_bad.append(b)

print("ID 차이 분포:", dict(diffs))
print("라벨 불일치:", len(label_bad), label_bad[:5])
print("파일명 패턴 이상:", len(badname), badname[:5])

from collections import Counter, defaultdict

task_cnt = Counter()
lens = defaultdict(list)
spk = defaultdict(set)

for p in files:
    d = np.load(p, allow_pickle=True)
    t = str(d['task'])
    T = d['X'].shape[1]
    task_cnt[t] += 1
    lens[t].append(T)
    spk[int(d['y'])].add(int(d['subject_id']))

print("과제별 파일 수:", dict(task_cnt))
print("화자 수 — HC:", len(spk[0]), "| PD:", len(spk[1]))
print()
for t in sorted(lens):
    a = np.array(lens[t])
    print(f"[{t}] 프레임 min={a.min()} / 중앙={int(np.median(a))} / max={a.max()}"
          f" | 150프레임(1.5초) 미만: {(a<150).sum()}개")

import numpy as np, glob, os, re

SRC = "/content/Shared-Parkinson"
DST = "/content/cut_1.5s"
WIN_SEC, STEP_SEC, FPS = 1.5, 0.75, 100
WIN, STEP = int(WIN_SEC*FPS), int(STEP_SEC*FPS)

n_seg, n_drop = 0, 0
for p in files:
    d = np.load(p, allow_pickle=True)
    X, T = d['X'], d['X'].shape[1]
    if T < WIN:
        n_drop += 1
        continue

    rel = os.path.relpath(p, SRC)
    outdir = os.path.join(DST, os.path.dirname(rel))
    os.makedirs(outdir, exist_ok=True)
    stem = os.path.basename(p)[:-4]

    for i, s in enumerate(range(0, T - WIN + 1, STEP), start=1):
        np.savez_compressed(
            os.path.join(outdir, f"{stem}-{i}.npz"),
            X=X[:, s:s+WIN].astype(np.float32),
            y=d['y'], subject_id=d['subject_id'], task=d['task'],
            src_file=stem, seg_index=np.int64(i), start_frame=np.int64(s),
        )
        n_seg += 1

print(f"조각 {n_seg}개 생성 | 짧아서 제외 {n_drop}개")

cut = glob.glob(os.path.join(DST, "**", "*.npz"), recursive=True)
print("총 조각:", len(cut))
d = np.load(cut[0], allow_pickle=True)
print(os.path.basename(cut[0]), "| X:", d['X'].shape, "| id:", int(d['subject_id']), "| y:", int(d['y']))
!du -sh {DST}

from collections import Counter, defaultdict
import numpy as np

cnt = Counter()
ylab = {}
for p in cut:
    d = np.load(p, allow_pickle=True)
    sid = int(d['subject_id'])
    cnt[sid] += 1
    ylab[sid] = int(d['y'])

v = np.array(list(cnt.values()))
print(f"화자 {len(cnt)}명 | 조각 min={v.min()} 중앙={int(np.median(v))} max={v.max()}")
print("HC 조각:", sum(c for s,c in cnt.items() if ylab[s]==0),
      "| PD 조각:", sum(c for s,c in cnt.items() if ylab[s]==1))
print("\n상위 5명:", cnt.most_common(5))
print("하위 5명:", cnt.most_common()[-5:])

few = sorted([(s,c) for s,c in cnt.items() if c <= 3], key=lambda x: x[1])
print(f"조각 3개 이하 화자: {len(few)}명")
print(few[:20])

!cd /content/cut_1.5s && zip -r /content/cut_1.5s.zip . -q
!ls -lh /content/cut_1.5s.zip

from google.colab import files
files.download('/content/cut_1.5s.zip')